app:
  address: ':5500'
  apiUrl: 'http://localhost:5500'
  mode: production
  tz: Asia/Shanghai
  printStack: false
  distribution:
    ip: 127.0.0.1
    port: 5300

database:
  dsn: "host=localhost user= dbname=chatpuppy port=5432 sslmode=disable TimeZone=UTC"
  debug: false

redis:
  address: 'localhost:6379'
  password: ''
  db: 3
