basePath: /
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.GroupCreateReq:
    properties:
      intro:
        type: string
      name:
        maxLength: 20
        minLength: 2
        type: string
    required:
    - name
    type: object
  model.MemberNonceRes:
    properties:
      nonce:
        type: string
    type: object
  model.MemberProfile:
    properties:
      address:
        type: string
      avatar:
        description: optional
        type: string
      intro:
        description: optional
        type: string
      nickname:
        description: optional
        type: string
    type: object
  model.MemberSigninRes:
    properties:
      profile:
        allOf:
        - $ref: '#/definitions/model.MemberProfile'
      token:
        type: string
    type: object
info:
  contact: {}
  title: ChatPuppy Api Doc
  version: "1.0"
paths:
  /group:
    post:
      consumes:
      - application/json
      description: create an group (need signature verify)
      operationId: GroupCreate
      parameters:
      - description: Group info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.GroupCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            $ref: '#/definitions/app.Response'
      summary: Group Create
      tags:
      - Group
  /member/{address}:
    get:
      consumes:
      - application/json
      description: Getting member's profile using address
      operationId: MemberProfile
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            $ref: '#/definitions/app.Response'
      summary: Member Profile
      tags:
      - Member
  /member/nonce/{address}:
    get:
      consumes:
      - application/json
      description: Getting nonce string to be signed
      operationId: MemberNonce
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.MemberNonceRes'
              type: object
      summary: Member Signin Nonce
      tags:
      - Member
  /memeber:
    post:
      consumes:
      - application/json
      operationId: MemberSignin
      produces:
      - application/json
      responses:
        "200":
          description: Response success
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.MemberSigninRes'
              type: object
      summary: Member Signin
      tags:
      - Member
swagger: "2.0"
